test
droidroot1995/DAFE_CPP_014 pull request #2
Opened 2020-10-09 07:02 UTC by Allaberdin

2020-11-04 01:57 UTC, LostPointer requested changes
накидал замечаний по быстрому)  но в принципе неплохо)

з.ы. ревью это не требование) если где-то не согласен/согласна то нужно обсудить)

2020-11-04 01:57 UTC, LostPointer commented on main.cpp
> +catch (exception& e)
const std::exception& - не меняется, так что лучше const

2020-11-04 01:57 UTC, LostPointer commented on Allaberdin_Bogdan/calculator/main.cpp
> +  cerr << "exception: " << e.what() << endl;
const - т.к. не меняется

2020-11-04 01:57 UTC, LostPointer commented on main.cpp
> +catch (exception& e)
и лучше удалить файлы, не из папки Allaberdin_Bogdan

2020-11-04 01:57 UTC, LostPointer commented on Allaberdin_Bogdan/calculator/Token.h
> +constexpr char quit = 'q';
константы лучше называть как-то по другому, например kQuit, сразу по коду будет видно что это константа
з.ы. так же можно использовать такую нотацию для enum'ов например:
```cpp
enum class SomeEnum {
  kFirst = 1,
  kSecond,
  kUnkown = 0,
}
```

2020-11-04 01:57 UTC, LostPointer commented on Allaberdin_Bogdan/calculator/Token.h
> +constexpr char quit = 'q';
и тут лучше использовать не константы а ```enum class```

2020-11-04 01:57 UTC, LostPointer commented on Allaberdin_Bogdan/calculator/Token.h
> +  char kind;
как сказал выше лучше например использовать enum class, например:
```cpp
enum class Kind {
  kQuit,
  kPrint,
  kNumber,
  kName,
  kLet,
}
```
так код будет понятнее

2020-11-04 01:57 UTC, LostPointer commented on Allaberdin_Bogdan/calculator/Token.h
> +  Token (char ch)
explicit

2020-11-04 01:57 UTC, LostPointer commented on Allaberdin_Bogdan/calculator/Token.h
> +  Token (char ch, double val)
можно избавится от предыдущего конструктора вот так:
```cpp
Token (char ch, double val = 0);
```
и не забыть explicit

2020-11-04 01:57 UTC, LostPointer commented on Allaberdin_Bogdan/calculator/Token_stream.cpp
> +void Token_stream::putback (Token t)
лучше назвать класс TokenStream
и метод тоже лучше назвать PutBack или put_back (мне больше нравиться первый вариант)

2020-11-04 01:57 UTC, LostPointer commented on Token_stream.cpp
> +  switch (ch)
лучше сделать функцию
```cpp
Token FromChar(const char char_token);
```
и внутри нее уже вставить этот switch
ну и с отступами поработать

2020-11-04 01:57 UTC, LostPointer commented on Variable.h
> +    vector<Variable> var_table;
используй map или unordered_map, где имя это ключ

2020-11-04 01:57 UTC, LostPointer commented on Variable.h
> +  Variable (string n, double v, bool c);
лучше не называть параметры одной буквой, может быть не понятно что они означают

2020-11-04 01:57 UTC, LostPointer commented on Variable.h
> +    bool is_declared (string s);
кажется лучше такое имя: has_value или HasValue (мне кажется более понятным )
и я за имена методов в формате SetValue, GetValue, DefineName (но это не обязательно, но это сразу дает понять что это метод, а не переменная)

2020-11-06 06:20 UTC, droidroot1995 approved these changes

2020-11-06 06:20 UTC, merged